jobs:
  action:
    name: Check
    runs-on: ubuntu-20.04

    steps:
      - name: Initialize
        uses: actions/checkout@v2
      - name: Pull Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./verify/run

name: Action

on:
  schedule:
    - cron: "15 */1 * * *"
